### PR TITLE
fix: dbus access

### PR DESCRIPTION
**Pull request by edfloreshz**

### CODE REVIEW

**Comment by edfloreshz** [comment]
Waiting for https://github.com/flathub-infra/flatpak-builder-lint/pull/430

**Comment by edfloreshz** [comment]
bot, build dev.edfloreshz.Tasks

**Comment by bbhtt** [comment]
You have to wait for a while before it gets published.  https://docs.flathub.org/docs/for-app-authors/linter#check-currently-published-exceptions

**Comment by edfloreshz** [comment]
Gotcha! Thanks

**Comment by edfloreshz** [comment]
bot, build dev.edfloreshz.Tasks

**Pull request merged**
